import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header/header'
import ShowCaseArea from '@/components/showcase-area/showcase-area'
import About from '@/components/about/about'
import Skills from '@/components/skills/skills'
import Services from '@/components/services/services'
import Portfolio from '@/components/portfolio/portfolio'
import Testimonials from '@/components/testimonials/testimonials'
import Contact from '@/components/contact/contact'
import Subscription from '@/components/subscription/subscription'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {

  useEffect(()=>{

    const header = document.querySelector("header");

    function activeLink(){
    let sections = document.querySelectorAll("section[id]");
    let passedSections = Array.from(sections).map((sct, i )=>{
      return {
        y: sct.getBoundingClientRect().top - header.offsetHeight,
        id: i, 
       };
    }).filter(sct => sct.y <= 0);

    let currSectionID = passedSections.at(-1).id; 
    links.forEach(l => l.classList.remove("active"));
    links[currSectionID].classList.add("active");

    }
    const links = document.querySelectorAll(".nav-link")
    

    globalThis.addEventListener("scroll", ()=>{
      activeLink();
    })
})
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"/>

      </Head>
      <Header />
      <main>
        <ShowCaseArea/>
        <About/>
        <Skills/> 
        <Services/>
        <Portfolio/>
        <Testimonials/>
        <Contact/>
        <Subscription />
       
      </main>
      <footer>
        <div className="container">
          <a href="#" className="logo">Mahmoud  <span>Zakaria</span></a>
          <p className="text">&copy; Copyrights 2023, All Rights Reserved.</p>
          <ul className="social-media">
            <li><a href="#" className="social-link"><i className="uil uil-facebook-f"></i></a></li>
            <li><a href="#" className="social-link"><i className="uil uil-twitter"></i></a></li>
            <li><a href="#" className="social-link"><i className="uil uil-github"></i></a></li>
          </ul>

        </div>
      </footer>
    </>
  )
}
