import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header/header'
import ShowCaseArea from '@/components/showcase-area/showcase-area'
import About from '@/components/about/about'
import Skills from '@/components/skills/skills'
import Services from '@/components/services/services'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"/>

      </Head>
      <Header />
      <main>
        <ShowCaseArea/>
        <About/>
        <Skills/> 
        <Services/>
       
       <div style={{height:"120vh"}}></div>
      </main>
    </>
  )
}
